import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ff5708",
        "primary-hover": "#e64d00",
        "primary-container": "#ff5708",
        "primary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#ffb59c",
        "on-primary": "#5c1900",
        "on-primary-container": "#511500",
        "background": "#131313",
        "on-background": "#e5e2e1",
        "surface": "#131313",
        "on-surface": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        "on-surface-variant": "#b4b5b5",
        "outline": "#ac897e",
        "outline-variant": "#262626",
        "outline-subtle": "#353534",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "secondary": "#c6c6c7",
        "secondary-container": "#454747",
        "tertiary": "#c8c6c5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        mono: ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
        display: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        button: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        body: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
};
export default config;
